spring:
  application:
    name: e-parking-challan
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    show_sql: true
    hibernate:
      ddl-auto: update
  server:
    port: 8085
